setTimeout(()=>{
    document.getElementById("display").innerHTML="10";
    setTimeout(()=>{
        document.getElementById("display").innerHTML="9";
        setTimeout(()=>{
            document.getElementById("display").innerHTML="8"
            setTimeout(()=>{
                document.getElementById("display").innerHTML="7"
                setTimeout(()=>{
                    document.getElementById("display").innerHTML="6"
                    setTimeout(()=>{
                        document.getElementById("display").innerHTML="5"
                        setTimeout(()=>{
                            document.getElementById("display").innerHTML="4"
                            setTimeout(()=>{
                                document.getElementById("display").innerHTML="3"
                                setTimeout(()=>{
                                    document.getElementById("display").innerHTML="2"
                                    setTimeout(()=>{
                                        document.getElementById("display").innerHTML="1"
                                        setTimeout(()=>{
                                            document.getElementById("display").innerHTML="🎉🎉Happy Independence Day🎉🎉"
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)